-- SendGrid order email observability: attempts + raw events + latest status view.

CREATE TABLE IF NOT EXISTS public.order_email_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tracking_id uuid NOT NULL DEFAULT gen_random_uuid(),
  sendgrid_message_id text,
  email_kind text NOT NULL CHECK (email_kind IN ('confirmation', 'download', 'pickup_reminder', 'completed', 'unknown')),
  event_type text NOT NULL,
  order_db_id integer REFERENCES public.orders2(id) ON DELETE SET NULL,
  square_order_id text,
  order_number text,
  recipient_email text,
  customer_square_id text,
  location_id text,
  source_service text,
  status text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'sent', 'delivered', 'opened', 'failed')),
  sent_at timestamptz,
  delivered_at timestamptz,
  opened_first_at timestamptz,
  opened_last_at timestamptz,
  open_count integer NOT NULL DEFAULT 0,
  last_event text,
  last_event_at timestamptz,
  failure_reason text,
  payload_meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT order_email_messages_tracking_id_key UNIQUE (tracking_id)
);

CREATE TABLE IF NOT EXISTS public.order_email_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sg_event_id text,
  tracking_id uuid REFERENCES public.order_email_messages(tracking_id) ON DELETE SET NULL,
  sendgrid_message_id text,
  event_type text NOT NULL,
  event_at timestamptz NOT NULL,
  recipient_email text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS order_email_events_sg_event_id_unique
  ON public.order_email_events (sg_event_id)
  WHERE sg_event_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS order_email_messages_order_kind_created_idx
  ON public.order_email_messages (order_db_id, email_kind, created_at DESC);

CREATE INDEX IF NOT EXISTS order_email_messages_tracking_id_idx
  ON public.order_email_messages (tracking_id);

CREATE INDEX IF NOT EXISTS order_email_messages_sendgrid_message_id_idx
  ON public.order_email_messages (sendgrid_message_id);

CREATE INDEX IF NOT EXISTS order_email_events_type_time_idx
  ON public.order_email_events (event_type, event_at DESC);

CREATE INDEX IF NOT EXISTS order_email_events_tracking_id_time_idx
  ON public.order_email_events (tracking_id, event_at DESC);

CREATE INDEX IF NOT EXISTS order_email_events_sendgrid_message_id_time_idx
  ON public.order_email_events (sendgrid_message_id, event_at DESC);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger
    WHERE tgname = 'trg_order_email_messages_updated_at'
  ) THEN
    CREATE TRIGGER trg_order_email_messages_updated_at
      BEFORE UPDATE ON public.order_email_messages
      FOR EACH ROW
      EXECUTE FUNCTION public.set_updated_at();
  END IF;
END $$;

CREATE OR REPLACE VIEW public.order_email_status_latest
WITH (security_invoker = on)
AS
WITH ranked AS (
  SELECT
    m.*,
    row_number() OVER (
      PARTITION BY m.order_db_id, m.email_kind
      ORDER BY COALESCE(m.last_event_at, m.created_at) DESC, m.id DESC
    ) AS rn
  FROM public.order_email_messages m
  WHERE m.order_db_id IS NOT NULL
)
SELECT
  r.id,
  r.tracking_id,
  r.sendgrid_message_id,
  r.email_kind,
  r.event_type,
  r.order_db_id,
  r.square_order_id,
  r.order_number,
  r.recipient_email,
  r.customer_square_id,
  r.location_id,
  r.source_service,
  r.status,
  r.sent_at,
  r.delivered_at,
  r.opened_first_at,
  r.opened_last_at,
  r.open_count,
  r.last_event,
  r.last_event_at,
  r.failure_reason,
  r.payload_meta,
  r.created_at,
  r.updated_at,
  (r.delivered_at IS NOT NULL) AS received,
  (COALESCE(r.open_count, 0) > 0 OR r.opened_first_at IS NOT NULL) AS opened
FROM ranked r
WHERE r.rn = 1;

ALTER TABLE public.order_email_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_email_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "order_email_messages_staff_read" ON public.order_email_messages;
CREATE POLICY "order_email_messages_staff_read"
  ON public.order_email_messages
  FOR SELECT
  TO authenticated
  USING (public.is_dashboard_staff());

DROP POLICY IF EXISTS "order_email_messages_service_all" ON public.order_email_messages;
CREATE POLICY "order_email_messages_service_all"
  ON public.order_email_messages
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "order_email_events_staff_read" ON public.order_email_events;
CREATE POLICY "order_email_events_staff_read"
  ON public.order_email_events
  FOR SELECT
  TO authenticated
  USING (public.is_dashboard_staff());

DROP POLICY IF EXISTS "order_email_events_service_all" ON public.order_email_events;
CREATE POLICY "order_email_events_service_all"
  ON public.order_email_events
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
