create type "public"."membership_status" as enum ('pending_checkout', 'active', 'past_due', 'canceled', 'cancelled', 'inactive', 'paused');

create type "public"."membership_tier" as enum ('creator', 'pro', 'studio_plus', 'test');

create sequence "public"."refund_queue_id_seq";

create sequence "public"."webhook_queue_id_seq";

drop trigger if exists "trg_bookings_updated_at" on "public"."bookings";

drop trigger if exists "trg_membership_tiers_updated_at" on "public"."membership_tiers";

drop trigger if exists "trg_memberships_updated_at" on "public"."memberships";

alter table "public"."booking_holds" drop constraint "booking_holds_no_overlap_excl";

alter table "public"."booking_holds" drop constraint "hold_time_order";

alter table "public"."bookings" drop constraint "booking_time_order";

alter table "public"."bookings" drop constraint "bookings_no_overlap_excl";

alter table "public"."customers" drop constraint "customers_user_id_fkey";

alter table "public"."memberships" drop constraint "memberships_status_check";

alter table "public"."memberships" drop constraint "memberships_user_id_key";

alter table "public"."bookings" drop constraint "bookings_status_check";

alter table "public"."bookings" drop constraint "bookings_user_id_fkey";

alter table "public"."membership_plan_variations" drop constraint "membership_plan_variations_tier_id_fkey";

drop view if exists "public"."credit_balance";

drop index if exists "public"."booking_holds_booking_id_idx";

drop index if exists "public"."booking_holds_hold_start_idx";

select 1; 
-- drop index if exists "public"."booking_holds_no_overlap_excl";

select 1; 
-- drop index if exists "public"."bookings_no_overlap_excl";

drop index if exists "public"."customers_user_id_key";

drop index if exists "public"."memberships_user_id_key";

drop index if exists "public"."customers_square_customer_id_idx";

drop index if exists "public"."customers_square_customer_id_key";

drop index if exists "public"."memberships_status_idx";


  create table "public"."cart_items" (
    "id" uuid not null default gen_random_uuid(),
    "cart_id" uuid,
    "variation_id" text not null,
    "product_name" text,
    "quantity" integer not null,
    "currency" text default 'USD'::text,
    "inventory_at_addition" integer,
    "price_locked_until" timestamp with time zone,
    "created_at" timestamp with time zone default now(),
    "product_id" text,
    "variation_name" text,
    "image_url" text,
    "price" integer not null default 0,
    "taxable" boolean not null default false,
    "weight" double precision
      );


alter table "public"."cart_items" enable row level security;


  create table "public"."cart_sessions" (
    "id" uuid not null default extensions.uuid_generate_v4(),
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "session_id" text not null,
    "user_id" uuid,
    "merged" boolean default false
      );


alter table "public"."cart_sessions" enable row level security;


  create table "public"."carts" (
    "id" uuid not null default gen_random_uuid(),
    "session_id" text not null,
    "user_id" uuid,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."carts" enable row level security;


  create table "public"."external_calendar_events" (
    "id" uuid not null default gen_random_uuid(),
    "provider" text not null,
    "calendar_id" text not null,
    "external_event_id" text not null,
    "title" text,
    "description" text,
    "location" text,
    "status" text not null default 'confirmed'::text,
    "start_time" timestamp with time zone not null,
    "end_time" timestamp with time zone not null,
    "active" boolean not null default true,
    "raw_payload" jsonb,
    "synced_at" timestamp with time zone not null default now(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."external_calendar_events" enable row level security;


  create table "public"."internal_errors" (
    "id" uuid not null default gen_random_uuid(),
    "timestamp" timestamp with time zone not null default now(),
    "level" text not null,
    "message" text not null,
    "stack_trace" text,
    "location" text,
    "file" text,
    "request_id" text,
    "user_id" uuid,
    "session_id" text,
    "metadata" jsonb,
    "is_resolved" boolean not null default false,
    "resolved_at" timestamp with time zone,
    "environment" text,
    "origin_ip" inet
      );



  create table "public"."kiosk" (
    "id" bigint generated by default as identity not null,
    "category_name" text,
    "display_order" bigint generated by default as identity not null
      );


alter table "public"."kiosk" enable row level security;


  create table "public"."links" (
    "id" uuid not null default extensions.uuid_generate_v4(),
    "orderId" text,
    "link" text,
    "expires_date" timestamp without time zone,
    "password" text,
    "email" text,
    "ssOrderId" bigint,
    "locationId" text default 'LMKTTKQG7R9JS'::text
      );



  create table "public"."orders" (
    "id" bigint generated by default as identity not null,
    "created" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "customerId" text,
    "orderId" text,
    "ssOrderId" bigint,
    "lineItems" jsonb[],
    "total" bigint default '0'::bigint,
    "state" text default 'INCOMPLETE'::text,
    "type" text default 'In Store'::text,
    "customerName" text,
    "customerEmail" text,
    "customerPhone" text,
    "internalNotes" text,
    "terminalStatus" text,
    "completed" text default 'INCOMPLETE'::text,
    "locationId" text default 'LMKTTKQG7R9JS'::text,
    "squareOrderJSON" jsonb,
    "shipping_status" text
      );



  create table "public"."orders2" (
    "id" bigint generated by default as identity not null,
    "created" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "customerId" text,
    "orderId" text,
    "ssOrderId" bigint,
    "lineItems" jsonb[],
    "total" bigint default '0'::bigint,
    "state" text default 'INCOMPLETE'::text,
    "type" text default 'In Store'::text,
    "name" text,
    "email" text,
    "phone" text,
    "internalNotes" text,
    "terminalStatus" text,
    "locationId" text default 'LMKTTKQG7R9JS'::text,
    "squareOrderJSON" jsonb,
    "shipping_status" text,
    "user_id" uuid default auth.uid(),
    "completed" boolean not null default false,
    "pickedup" boolean default false,
    "isServiceOrder" boolean default false,
    "confirmationSent" boolean default false,
    "refunded_amount" bigint,
    "public_order_token" text,
    "fulfillment_meta" jsonb
      );


alter table "public"."orders2" enable row level security;


  create table "public"."ordersTest" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "orderId" text,
    "squareOrderJSON" jsonb
      );



  create table "public"."print_jobs" (
    "id" uuid not null default gen_random_uuid(),
    "order_id" bigint not null,
    "order_square_id" text,
    "location_id" text not null,
    "job_type" text not null default 'order_sheet'::text,
    "status" text not null default 'queued'::text,
    "attempts" integer not null default 0,
    "printed_at" timestamp with time zone,
    "last_error" text,
    "printer_name" text,
    "claimed_by" text,
    "claimed_at" timestamp with time zone,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );



  create table "public"."products" (
    "id" uuid not null default gen_random_uuid(),
    "square_variation_id" text not null,
    "name" text,
    "price" integer not null,
    "currency" text default 'USD'::text,
    "is_active" boolean default true,
    "updated_at" timestamp with time zone default now()
      );



  create table "public"."refund_queue" (
    "id" bigint not null default nextval('public.refund_queue_id_seq'::regclass),
    "order_id" text not null,
    "order_db_id" integer not null,
    "amount" integer not null,
    "reason" text,
    "status" text not null default 'pending'::text,
    "initiated_by" uuid,
    "idempotency_key" uuid not null default gen_random_uuid(),
    "square_refund_id" text,
    "square_response" jsonb,
    "error_message" text,
    "created_at" timestamp with time zone not null default now(),
    "processed_at" timestamp with time zone,
    "updated_at" timestamp with time zone not null default now()
      );



  create table "public"."service_categories" (
    "id" bigint generated always as identity not null,
    "category_id" text not null,
    "name" text not null,
    "active" boolean default true,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."service_categories" enable row level security;


  create table "public"."services" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "square_id" text,
    "name" text,
    "description" text,
    "category" bigint,
    "display_order" bigint generated by default as identity not null
      );


alter table "public"."services" enable row level security;


  create table "public"."settings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "locationId" text default ''::text,
    "orderFulfilled" text,
    "orderConfirmation" text,
    "orderDownload" text,
    "orderPickupReminder" text,
    "orderRefund" text,
    "membershipWaitlistInvite" text,
    "membershipCheckoutActivation" text
      );


alter table "public"."settings" enable row level security;


  create table "public"."shipping_package_profiles" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "square_variation_id" text,
    "square_item_id" text,
    "square_category_id" text,
    "is_default" boolean not null default false,
    "package_code" text not null default 'package'::text,
    "length_in" numeric(10,2) not null,
    "width_in" numeric(10,2) not null,
    "height_in" numeric(10,2) not null,
    "weight_lb" numeric(10,2),
    "priority" integer not null default 100,
    "metadata" jsonb not null default '{}'::jsonb,
    "active" boolean not null default true,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "locationId" text
      );


alter table "public"."shipping_package_profiles" enable row level security;


  create table "public"."shop" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."shop" enable row level security;


  create table "public"."webhook_queue" (
    "id" bigint not null default nextval('public.webhook_queue_id_seq'::regclass),
    "topic" text not null,
    "payload" jsonb not null,
    "created_at" timestamp with time zone not null default now(),
    "processed" boolean not null default false,
    "processed_at" timestamp with time zone,
    "attempts" integer not null default 0
      );


alter table "public"."booking_holds" add column "cash_cost_cents" integer;

alter table "public"."booking_holds" add column "credits_cost" numeric;

alter table "public"."booking_holds" add column "hold_range" tstzrange generated always as (tstzrange(hold_start, hold_end, '[)'::text)) stored;

alter table "public"."bookings" drop column "time_range";

alter table "public"."bookings" add column "time_range" tstzrange generated always as (tstzrange(start_time, end_time, '[)'::text)) stored;

alter table "public"."bookings" alter column "credits_estimated" set data type numeric using "credits_estimated"::numeric;

alter table "public"."bookings" alter column "credits_final" set data type numeric using "credits_final"::numeric;

alter table "public"."membership_plan_variations" drop column "created_at";

alter table "public"."membership_plan_variations" alter column "provider_plan_variation_id" set not null;

alter table "public"."membership_tiers" alter column "booking_window_days" drop default;

alter table "public"."membership_tiers" alter column "max_bank" set not null;

alter table "public"."membership_tiers" alter column "peak_multiplier" drop default;

alter table "public"."membership_tiers" alter column "peak_multiplier" set data type numeric using "peak_multiplier"::numeric;

alter table "public"."memberships" alter column "cadence" set default 'monthly'::text;

alter table "public"."memberships" alter column "status" set default 'pending_checkout'::public.membership_status;

alter table "public"."memberships" alter column "status" set data type public.membership_status using "status"::public.membership_status;

alter table "public"."memberships" alter column "tier" set not null;

alter table "public"."system_config" enable row level security;

alter sequence "public"."refund_queue_id_seq" owned by "public"."refund_queue"."id";

alter sequence "public"."webhook_queue_id_seq" owned by "public"."webhook_queue"."id";

CREATE INDEX booking_holds_time_idx ON public.booking_holds USING btree (hold_start, hold_end);

select 1; 
-- CREATE INDEX bookings_no_overlap_confirmed ON public.bookings USING gist (time_range) WHERE (status = 'confirmed'::text);

CREATE INDEX bookings_time_idx ON public.bookings USING btree (start_time, end_time);

CREATE INDEX bookings_user_idx ON public.bookings USING btree (user_id, created_at DESC);

CREATE UNIQUE INDEX cart_items_cart_variation_key ON public.cart_items USING btree (cart_id, variation_id);

CREATE UNIQUE INDEX cart_items_pkey ON public.cart_items USING btree (id);

CREATE UNIQUE INDEX cart_sessions_cookie_id_key ON public.cart_sessions USING btree (session_id);

CREATE UNIQUE INDEX cart_sessions_pkey ON public.cart_sessions USING btree (id);

CREATE UNIQUE INDEX cart_sessions_session_id_key ON public.cart_sessions USING btree (session_id);

CREATE INDEX cart_sessions_user_id_idx ON public.cart_sessions USING btree (user_id) WHERE (user_id IS NOT NULL);

CREATE UNIQUE INDEX carts_pkey ON public.carts USING btree (id);

CREATE UNIQUE INDEX credits_ledger_unique_invoice ON public.credits_ledger USING btree (user_id, reason, external_ref) WHERE (external_ref IS NOT NULL);

CREATE INDEX customers_email_lower_idx ON public.customers USING btree (lower(email));

CREATE INDEX customers_phone_idx ON public.customers USING btree (phone);

CREATE INDEX external_calendar_events_active_time_idx ON public.external_calendar_events USING btree (active, start_time, end_time);

CREATE UNIQUE INDEX external_calendar_events_pkey ON public.external_calendar_events USING btree (id);

CREATE INDEX external_calendar_events_provider_calendar_time_idx ON public.external_calendar_events USING btree (provider, calendar_id, start_time);

CREATE UNIQUE INDEX external_calendar_events_provider_event_uidx ON public.external_calendar_events USING btree (provider, calendar_id, external_event_id);

select 1; 
-- CREATE INDEX holds_no_overlap ON public.booking_holds USING gist (hold_range);

CREATE INDEX idx_refund_queue_created_at ON public.refund_queue USING btree (created_at DESC);

CREATE INDEX idx_refund_queue_order_db_id ON public.refund_queue USING btree (order_db_id);

CREATE INDEX idx_refund_queue_order_id ON public.refund_queue USING btree (order_id);

CREATE INDEX idx_refund_queue_status ON public.refund_queue USING btree (status);

CREATE INDEX idx_webhook_queue_processed_created_at ON public.webhook_queue USING btree (processed, created_at);

CREATE UNIQUE INDEX internal_errors_pkey ON public.internal_errors USING btree (id);

CREATE UNIQUE INDEX kiosk_pkey ON public.kiosk USING btree (id);

CREATE UNIQUE INDEX links_pkey ON public.links USING btree (id);

CREATE UNIQUE INDEX "links_ssOrderId_key" ON public.links USING btree ("ssOrderId");

CREATE UNIQUE INDEX membership_plan_variations_provider_provider_plan_variation_key ON public.membership_plan_variations USING btree (provider, provider_plan_variation_id);

CREATE UNIQUE INDEX memberships_one_per_user ON public.memberships USING btree (user_id);

CREATE INDEX mpv_lookup_idx ON public.membership_plan_variations USING btree (provider, provider_plan_variation_id);

CREATE INDEX mpv_tier_cadence_idx ON public.membership_plan_variations USING btree (tier_id, cadence, provider, active, visible);

CREATE UNIQUE INDEX one_item_per_variation ON public.cart_items USING btree (cart_id, variation_id);

CREATE INDEX "orders2_customerId_idx" ON public.orders2 USING btree ("customerId");

CREATE UNIQUE INDEX "orders2_orderId_key" ON public.orders2 USING btree ("orderId");

CREATE UNIQUE INDEX orders2_pkey ON public.orders2 USING btree (id);

CREATE UNIQUE INDEX orders2_public_order_token_key ON public.orders2 USING btree (public_order_token) WHERE (public_order_token IS NOT NULL);

CREATE UNIQUE INDEX "orders2_ssOrderId_key" ON public.orders2 USING btree ("ssOrderId");

CREATE UNIQUE INDEX "ordersTest_pkey" ON public."ordersTest" USING btree (id);

CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (id);

CREATE UNIQUE INDEX print_jobs_pkey ON public.print_jobs USING btree (id);

CREATE UNIQUE INDEX print_jobs_unique_order_type ON public.print_jobs USING btree (order_id, job_type);

CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id);

CREATE UNIQUE INDEX products_square_variation_id_key ON public.products USING btree (square_variation_id);

CREATE UNIQUE INDEX refund_queue_pkey ON public.refund_queue USING btree (id);

CREATE UNIQUE INDEX service_categories_category_id_key ON public.service_categories USING btree (category_id);

CREATE UNIQUE INDEX service_categories_pkey ON public.service_categories USING btree (id);

CREATE UNIQUE INDEX services_pkey ON public.services USING btree (id);

CREATE UNIQUE INDEX settings_pkey ON public.settings USING btree (id);

CREATE INDEX shipping_package_profiles_category_idx ON public.shipping_package_profiles USING btree (square_category_id) WHERE (square_category_id IS NOT NULL);

CREATE INDEX shipping_package_profiles_item_idx ON public.shipping_package_profiles USING btree (square_item_id) WHERE (square_item_id IS NOT NULL);

CREATE INDEX shipping_package_profiles_location_idx ON public.shipping_package_profiles USING btree ("locationId") WHERE ("locationId" IS NOT NULL);

CREATE UNIQUE INDEX shipping_package_profiles_one_active_default_per_location_idx ON public.shipping_package_profiles USING btree (COALESCE("locationId", '__global__'::text)) WHERE ((is_default = true) AND (active = true));

CREATE UNIQUE INDEX shipping_package_profiles_pkey ON public.shipping_package_profiles USING btree (id);

CREATE INDEX shipping_package_profiles_variation_idx ON public.shipping_package_profiles USING btree (square_variation_id) WHERE (square_variation_id IS NOT NULL);

CREATE UNIQUE INDEX shop_pkey ON public.shop USING btree (id);

CREATE UNIQUE INDEX unique_cart_per_session ON public.cart_sessions USING btree (session_id);

CREATE UNIQUE INDEX webhook_queue_pkey ON public.webhook_queue USING btree (id);

CREATE INDEX customers_square_customer_id_idx ON public.customers USING btree (square_customer_id);

CREATE UNIQUE INDEX customers_square_customer_id_key ON public.customers USING btree (square_customer_id);

CREATE INDEX memberships_status_idx ON public.memberships USING btree (status);

alter table "public"."cart_items" add constraint "cart_items_pkey" PRIMARY KEY using index "cart_items_pkey";

alter table "public"."cart_sessions" add constraint "cart_sessions_pkey" PRIMARY KEY using index "cart_sessions_pkey";

alter table "public"."carts" add constraint "carts_pkey" PRIMARY KEY using index "carts_pkey";

alter table "public"."external_calendar_events" add constraint "external_calendar_events_pkey" PRIMARY KEY using index "external_calendar_events_pkey";

alter table "public"."internal_errors" add constraint "internal_errors_pkey" PRIMARY KEY using index "internal_errors_pkey";

alter table "public"."kiosk" add constraint "kiosk_pkey" PRIMARY KEY using index "kiosk_pkey";

alter table "public"."links" add constraint "links_pkey" PRIMARY KEY using index "links_pkey";

alter table "public"."orders" add constraint "orders_pkey" PRIMARY KEY using index "orders_pkey";

alter table "public"."orders2" add constraint "orders2_pkey" PRIMARY KEY using index "orders2_pkey";

alter table "public"."ordersTest" add constraint "ordersTest_pkey" PRIMARY KEY using index "ordersTest_pkey";

alter table "public"."print_jobs" add constraint "print_jobs_pkey" PRIMARY KEY using index "print_jobs_pkey";

alter table "public"."products" add constraint "products_pkey" PRIMARY KEY using index "products_pkey";

alter table "public"."refund_queue" add constraint "refund_queue_pkey" PRIMARY KEY using index "refund_queue_pkey";

alter table "public"."service_categories" add constraint "service_categories_pkey" PRIMARY KEY using index "service_categories_pkey";

alter table "public"."services" add constraint "services_pkey" PRIMARY KEY using index "services_pkey";

alter table "public"."settings" add constraint "settings_pkey" PRIMARY KEY using index "settings_pkey";

alter table "public"."shipping_package_profiles" add constraint "shipping_package_profiles_pkey" PRIMARY KEY using index "shipping_package_profiles_pkey";

alter table "public"."shop" add constraint "shop_pkey" PRIMARY KEY using index "shop_pkey";

alter table "public"."webhook_queue" add constraint "webhook_queue_pkey" PRIMARY KEY using index "webhook_queue_pkey";

alter table "public"."booking_holds" add constraint "booking_holds_hold_type_check" CHECK ((hold_type = 'overnight'::text)) not valid;

alter table "public"."booking_holds" validate constraint "booking_holds_hold_type_check";

alter table "public"."booking_holds" add constraint "holds_no_overlap" EXCLUDE USING gist (hold_range WITH &&);

alter table "public"."bookings" add constraint "bookings_no_overlap_confirmed" EXCLUDE USING gist (time_range WITH &&) WHERE ((status = 'confirmed'::text));

alter table "public"."cart_items" add constraint "cart_items_cart_id_fkey" FOREIGN KEY (cart_id) REFERENCES public.cart_sessions(id) not valid;

alter table "public"."cart_items" validate constraint "cart_items_cart_id_fkey";

alter table "public"."cart_items" add constraint "cart_items_quantity_check" CHECK ((quantity > 0)) not valid;

alter table "public"."cart_items" validate constraint "cart_items_quantity_check";

alter table "public"."cart_sessions" add constraint "cart_sessions_cookie_id_key" UNIQUE using index "cart_sessions_cookie_id_key";

alter table "public"."cart_sessions" add constraint "cart_sessions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."cart_sessions" validate constraint "cart_sessions_user_id_fkey";

alter table "public"."customers" add constraint "customers_square_customer_id_key" UNIQUE using index "customers_square_customer_id_key";

alter table "public"."external_calendar_events" add constraint "external_calendar_events_provider_check" CHECK ((provider = 'google'::text)) not valid;

alter table "public"."external_calendar_events" validate constraint "external_calendar_events_provider_check";

alter table "public"."external_calendar_events" add constraint "external_calendar_events_time_order" CHECK ((end_time > start_time)) not valid;

alter table "public"."external_calendar_events" validate constraint "external_calendar_events_time_order";

alter table "public"."internal_errors" add constraint "internal_errors_level_check" CHECK ((level = ANY (ARRAY['error'::text, 'warn'::text, 'info'::text, 'debug'::text]))) not valid;

alter table "public"."internal_errors" validate constraint "internal_errors_level_check";

alter table "public"."internal_errors" add constraint "internal_errors_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."internal_errors" validate constraint "internal_errors_user_id_fkey";

alter table "public"."links" add constraint "links_ssOrderId_key" UNIQUE using index "links_ssOrderId_key";

alter table "public"."membership_plan_variations" add constraint "membership_plan_variations_provider_provider_plan_variation_key" UNIQUE using index "membership_plan_variations_provider_provider_plan_variation_key";

alter table "public"."orders2" add constraint "orders2_orderId_key" UNIQUE using index "orders2_orderId_key";

alter table "public"."orders2" add constraint "orders2_ssOrderId_key" UNIQUE using index "orders2_ssOrderId_key";

alter table "public"."orders2" add constraint "orders2_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."orders2" validate constraint "orders2_user_id_fkey";

alter table "public"."products" add constraint "products_square_variation_id_key" UNIQUE using index "products_square_variation_id_key";

alter table "public"."refund_queue" add constraint "refund_queue_amount_check" CHECK ((amount > 0)) not valid;

alter table "public"."refund_queue" validate constraint "refund_queue_amount_check";

alter table "public"."refund_queue" add constraint "refund_queue_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text, 'canceled'::text]))) not valid;

alter table "public"."refund_queue" validate constraint "refund_queue_status_check";

alter table "public"."service_categories" add constraint "service_categories_category_id_key" UNIQUE using index "service_categories_category_id_key";

alter table "public"."services" add constraint "services_category_fkey" FOREIGN KEY (category) REFERENCES public.kiosk(id) not valid;

alter table "public"."services" validate constraint "services_category_fkey";

alter table "public"."shipping_package_profiles" add constraint "shipping_package_profiles_dimensions_positive" CHECK (((length_in > (0)::numeric) AND (width_in > (0)::numeric) AND (height_in > (0)::numeric))) not valid;

alter table "public"."shipping_package_profiles" validate constraint "shipping_package_profiles_dimensions_positive";

alter table "public"."shipping_package_profiles" add constraint "shipping_package_profiles_scope_required" CHECK (((is_default = true) OR (square_variation_id IS NOT NULL) OR (square_item_id IS NOT NULL) OR (square_category_id IS NOT NULL))) not valid;

alter table "public"."shipping_package_profiles" validate constraint "shipping_package_profiles_scope_required";

alter table "public"."bookings" add constraint "bookings_status_check" CHECK ((status = ANY (ARRAY['requested'::text, 'confirmed'::text, 'canceled'::text, 'cancelled'::text, 'completed'::text, 'declined'::text, 'pending_payment'::text, 'no_show'::text]))) not valid;

alter table "public"."bookings" validate constraint "bookings_status_check";

alter table "public"."bookings" add constraint "bookings_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."bookings" validate constraint "bookings_user_id_fkey";

alter table "public"."membership_plan_variations" add constraint "membership_plan_variations_tier_id_fkey" FOREIGN KEY (tier_id) REFERENCES public.membership_tiers(id) ON DELETE CASCADE not valid;

alter table "public"."membership_plan_variations" validate constraint "membership_plan_variations_tier_id_fkey";

set check_function_bodies = off;

create or replace view "public"."active_carts" as  SELECT cart_sessions.id,
    cart_sessions.created_at,
    cart_sessions.updated_at,
    cart_sessions.session_id AS cookie_id,
    cart_sessions.user_id,
    cart_sessions.merged
   FROM public.cart_sessions
  WHERE (cart_sessions.updated_at > (now() - '30 days'::interval));


CREATE OR REPLACE FUNCTION public.claim_print_job(p_job_id uuid, p_printer_name text, p_claimed_by text)
 RETURNS TABLE(id uuid, order_id bigint, order_square_id text, location_id text, job_type text, status text, attempts integer)
 LANGUAGE plpgsql
AS $function$
begin
  return query
  update public.print_jobs
  set status = 'printing',
      printer_name = p_printer_name,
      claimed_by = p_claimed_by,
      claimed_at = now(),
      attempts = attempts + 1,
      updated_at = now()
  where public.print_jobs.id = p_job_id
    and status = 'queued'
  returning
    public.print_jobs.id,
    public.print_jobs.order_id,
    public.print_jobs.order_square_id,
    public.print_jobs.location_id,
    public.print_jobs.job_type,
    public.print_jobs.status,
    public.print_jobs.attempts;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.create_confirmed_booking_with_burn(p_user_id uuid, p_customer_id uuid, p_start_time timestamp with time zone, p_end_time timestamp with time zone, p_notes text, p_request_hold boolean, p_credits_needed numeric, p_consume_paid_hold boolean DEFAULT false)
 RETURNS TABLE(booking_id uuid, hold_id uuid, credits_burned numeric, new_balance numeric)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_booking_id     uuid;
  v_hold_id        uuid;
  v_balance        numeric;
  v_burned         numeric;
  v_hold_start     timestamptz;
  v_hold_end       timestamptz;
  v_membership_id  uuid;
  v_hold_balance   integer;
BEGIN
  -- Serialize booking burns per-user by locking membership row.
  SELECT m.id
    INTO v_membership_id
    FROM public.memberships m
   WHERE m.user_id = p_user_id
   LIMIT 1
   FOR UPDATE;

  IF v_membership_id IS NULL THEN
    RAISE EXCEPTION 'Membership required for user %', p_user_id;
  END IF;

  SELECT COALESCE(SUM(l.delta), 0)
    INTO v_balance
    FROM public.credits_ledger l
   WHERE l.user_id = p_user_id
     AND (l.expires_at IS NULL OR l.expires_at > now());

  IF v_balance < p_credits_needed THEN
    RAISE EXCEPTION 'Insufficient credits: have %, need %', v_balance, p_credits_needed;
  END IF;

  IF p_consume_paid_hold AND NOT p_request_hold THEN
    RAISE EXCEPTION 'Paid hold consumption requires request_hold=true';
  END IF;

  IF p_consume_paid_hold THEN
    SELECT COALESCE(SUM(h.delta), 0)
      INTO v_hold_balance
      FROM public.hold_ledger h
     WHERE h.user_id = p_user_id
       AND (h.expires_at IS NULL OR h.expires_at > now());

    IF v_hold_balance < 1 THEN
      RAISE EXCEPTION 'Insufficient hold credits';
    END IF;
  END IF;

  INSERT INTO public.bookings (
    user_id, customer_id, start_time, end_time,
    status, notes, credits_estimated, credits_burned
  )
  VALUES (
    p_user_id, p_customer_id, p_start_time, p_end_time,
    'confirmed', p_notes, p_credits_needed, p_credits_needed
  )
  RETURNING id INTO v_booking_id;

  v_burned := p_credits_needed;
  INSERT INTO public.credits_ledger (user_id, delta, reason, external_ref)
  VALUES (p_user_id, -v_burned, 'booking_burn', v_booking_id::text);

  IF p_request_hold THEN
    v_hold_start := p_end_time;
    v_hold_end   := ((p_end_time AT TIME ZONE 'America/Los_Angeles')::date
                      + INTERVAL '1 day'
                      + INTERVAL '10 hours')
                      AT TIME ZONE 'America/Los_Angeles';

    INSERT INTO public.booking_holds (booking_id, hold_start, hold_end, hold_type)
    VALUES (v_booking_id, v_hold_start, v_hold_end, 'overnight')
    RETURNING id INTO v_hold_id;
  END IF;

  IF p_consume_paid_hold THEN
    INSERT INTO public.hold_ledger (user_id, delta, reason, external_ref, metadata)
    VALUES (
      p_user_id,
      -1,
      'booking_hold',
      v_booking_id::text,
      jsonb_build_object(
        'source', 'booking_create',
        'booking_id', v_booking_id,
        'hold_id', v_hold_id
      )
    );
  END IF;

  SELECT COALESCE(SUM(l.delta), 0)
    INTO v_balance
    FROM public.credits_ledger l
   WHERE l.user_id = p_user_id
     AND (l.expires_at IS NULL OR l.expires_at > now());

  RETURN QUERY SELECT v_booking_id, v_hold_id, v_burned, v_balance;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_membership_by_square_variation(variation_id text)
 RETURNS TABLE(tier_id text, cadence text, credits_per_month integer, booking_window_days integer, max_bank integer, peak_multiplier numeric, holds_included integer, price_cents integer, currency text)
 LANGUAGE sql
 STABLE
AS $function$
  select
    t.id as tier_id,
    v.cadence,
    v.credits_per_month,
    t.booking_window_days,
    t.max_bank,
    t.peak_multiplier,
    t.holds_included,
    v.price_cents,
    v.currency
  from public.membership_plan_variations v
  join public.membership_tiers t on t.id = v.tier_id
  where v.provider = 'square'
    and v.provider_plan_variation_id = variation_id
    and v.active = true
    and t.active = true
  limit 1;
$function$
;

CREATE OR REPLACE FUNCTION public.get_secret(secret_name text)
 RETURNS text
 LANGUAGE plpgsql
AS $function$
DECLARE
    decrypted text;
BEGIN
    -- Ensure only authorized roles can execute this function
    IF current_setting('request.jwt.claims', true)::jsonb->>'role' = 'service_role' THEN
        SELECT decrypted_secret
        INTO decrypted
        FROM vault.decrypted_secrets
        WHERE name = secret_name;
        RETURN decrypted;
    ELSE
        RAISE EXCEPTION 'Access denied: only service_role user can execute this function.';
    END IF;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.increment_refunded_amount(p_order_id text, p_amount bigint)
 RETURNS void
 LANGUAGE sql
AS $function$
  update orders2
  set refunded_amount = coalesce(refunded_amount, 0)::int8 + p_amount
  where "orderId" = p_order_id;
$function$
;

create or replace view "public"."links_with_customers" as  SELECT l.id,
    l."orderId",
    l.link,
    l.expires_date,
    l.password,
    l.email,
    l."ssOrderId",
    c.id AS db_customer_id,
    c.square_customer_id,
    c.first_name,
    c.last_name,
    c.email AS customer_email,
    c.phone AS customer_phone,
    c.lab_notes
   FROM (public.links l
     LEFT JOIN public.customers c ON ((c.email = l.email)));


create or replace view "public"."orders_with_customers" as  SELECT o.id,
    o.created,
    o."customerId",
    o."orderId",
    o."ssOrderId",
    o."lineItems",
    o.total,
    o.state,
    o.type,
    o.name,
    o.email,
    o.phone,
    o."internalNotes",
    o."terminalStatus",
    o."locationId",
    o."squareOrderJSON",
    o.shipping_status,
    o.user_id,
    o.completed,
    o.pickedup,
    o."isServiceOrder",
    o."confirmationSent",
    o.refunded_amount,
    c.id AS db_customer_id,
    c.square_customer_id,
    c.first_name,
    c.last_name,
    c.email AS customer_email,
    c.phone AS customer_phone,
    c.lab_notes
   FROM (public.orders2 o
     LEFT JOIN public.customers c ON ((c.square_customer_id = o."customerId")));


CREATE OR REPLACE FUNCTION public.queue_print_job_on_order_completed()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  -- only queue when eligible
  if (
    new."isServiceOrder" = true
    and new."state" = 'COMPLETED'
    and new."locationId" is not null
    and new."customerId" is not null  -- change to your actual "customer attached" signal
  ) then
    insert into print_jobs (order_id, order_square_id, location_id, job_type, status)
    values (new.id, new."orderId", new."locationId", 'order_sheet', 'queued')
    on conflict (order_id, job_type) do nothing;
  end if;

  return new;
end;
$function$
;

create or replace view "public"."refund_queue_with_details" as  SELECT rq.id,
    rq.order_id,
    rq.order_db_id,
    rq.amount,
    rq.reason,
    rq.status,
    rq.initiated_by,
    rq.idempotency_key,
    rq.square_refund_id,
    rq.square_response,
    rq.error_message,
    rq.created_at,
    rq.processed_at,
    rq.updated_at,
    o2.total AS order_total,
    o2.refunded_amount AS order_refunded_amount,
    o2.state AS order_state,
    o2."customerId",
    o2."locationId",
    o2."squareOrderJSON",
    owc.first_name,
    owc.last_name,
    owc.customer_email
   FROM ((public.refund_queue rq
     JOIN public.orders2 o2 ON ((o2.id = rq.order_db_id)))
     LEFT JOIN public.orders_with_customers owc ON ((owc.id = rq.order_db_id)));


CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.set_user_id()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  IF (NEW.user_id IS NULL) THEN
    NEW.user_id := auth.uid();
  END IF;
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.touch_shipping_package_profiles_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.update_refund_queue_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$ BEGIN NEW.updated_at = NOW(); RETURN NEW; END; $function$
;

CREATE OR REPLACE FUNCTION public.update_timestamp()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
   NEW.updated_at = now();
   RETURN NEW;
END;
$function$
;

create or replace view "public"."credit_balance" as  SELECT credits_ledger.user_id,
    (COALESCE(sum(credits_ledger.delta), (0)::numeric))::numeric(10,2) AS balance
   FROM public.credits_ledger
  WHERE ((credits_ledger.expires_at IS NULL) OR (credits_ledger.expires_at > now()))
  GROUP BY credits_ledger.user_id;


grant delete on table "public"."cart_items" to "anon";

grant insert on table "public"."cart_items" to "anon";

grant references on table "public"."cart_items" to "anon";

grant select on table "public"."cart_items" to "anon";

grant trigger on table "public"."cart_items" to "anon";

grant truncate on table "public"."cart_items" to "anon";

grant update on table "public"."cart_items" to "anon";

grant delete on table "public"."cart_items" to "authenticated";

grant insert on table "public"."cart_items" to "authenticated";

grant references on table "public"."cart_items" to "authenticated";

grant select on table "public"."cart_items" to "authenticated";

grant trigger on table "public"."cart_items" to "authenticated";

grant truncate on table "public"."cart_items" to "authenticated";

grant update on table "public"."cart_items" to "authenticated";

grant delete on table "public"."cart_items" to "service_role";

grant insert on table "public"."cart_items" to "service_role";

grant references on table "public"."cart_items" to "service_role";

grant select on table "public"."cart_items" to "service_role";

grant trigger on table "public"."cart_items" to "service_role";

grant truncate on table "public"."cart_items" to "service_role";

grant update on table "public"."cart_items" to "service_role";

grant delete on table "public"."cart_sessions" to "anon";

grant insert on table "public"."cart_sessions" to "anon";

grant references on table "public"."cart_sessions" to "anon";

grant select on table "public"."cart_sessions" to "anon";

grant trigger on table "public"."cart_sessions" to "anon";

grant truncate on table "public"."cart_sessions" to "anon";

grant update on table "public"."cart_sessions" to "anon";

grant delete on table "public"."cart_sessions" to "authenticated";

grant insert on table "public"."cart_sessions" to "authenticated";

grant references on table "public"."cart_sessions" to "authenticated";

grant select on table "public"."cart_sessions" to "authenticated";

grant trigger on table "public"."cart_sessions" to "authenticated";

grant truncate on table "public"."cart_sessions" to "authenticated";

grant update on table "public"."cart_sessions" to "authenticated";

grant delete on table "public"."cart_sessions" to "service_role";

grant insert on table "public"."cart_sessions" to "service_role";

grant references on table "public"."cart_sessions" to "service_role";

grant select on table "public"."cart_sessions" to "service_role";

grant trigger on table "public"."cart_sessions" to "service_role";

grant truncate on table "public"."cart_sessions" to "service_role";

grant update on table "public"."cart_sessions" to "service_role";

grant delete on table "public"."carts" to "anon";

grant insert on table "public"."carts" to "anon";

grant references on table "public"."carts" to "anon";

grant select on table "public"."carts" to "anon";

grant trigger on table "public"."carts" to "anon";

grant truncate on table "public"."carts" to "anon";

grant update on table "public"."carts" to "anon";

grant delete on table "public"."carts" to "authenticated";

grant insert on table "public"."carts" to "authenticated";

grant references on table "public"."carts" to "authenticated";

grant select on table "public"."carts" to "authenticated";

grant trigger on table "public"."carts" to "authenticated";

grant truncate on table "public"."carts" to "authenticated";

grant update on table "public"."carts" to "authenticated";

grant delete on table "public"."carts" to "service_role";

grant insert on table "public"."carts" to "service_role";

grant references on table "public"."carts" to "service_role";

grant select on table "public"."carts" to "service_role";

grant trigger on table "public"."carts" to "service_role";

grant truncate on table "public"."carts" to "service_role";

grant update on table "public"."carts" to "service_role";

grant delete on table "public"."external_calendar_events" to "anon";

grant insert on table "public"."external_calendar_events" to "anon";

grant references on table "public"."external_calendar_events" to "anon";

grant select on table "public"."external_calendar_events" to "anon";

grant trigger on table "public"."external_calendar_events" to "anon";

grant truncate on table "public"."external_calendar_events" to "anon";

grant update on table "public"."external_calendar_events" to "anon";

grant delete on table "public"."external_calendar_events" to "authenticated";

grant insert on table "public"."external_calendar_events" to "authenticated";

grant references on table "public"."external_calendar_events" to "authenticated";

grant select on table "public"."external_calendar_events" to "authenticated";

grant trigger on table "public"."external_calendar_events" to "authenticated";

grant truncate on table "public"."external_calendar_events" to "authenticated";

grant update on table "public"."external_calendar_events" to "authenticated";

grant delete on table "public"."external_calendar_events" to "service_role";

grant insert on table "public"."external_calendar_events" to "service_role";

grant references on table "public"."external_calendar_events" to "service_role";

grant select on table "public"."external_calendar_events" to "service_role";

grant trigger on table "public"."external_calendar_events" to "service_role";

grant truncate on table "public"."external_calendar_events" to "service_role";

grant update on table "public"."external_calendar_events" to "service_role";

grant delete on table "public"."internal_errors" to "anon";

grant insert on table "public"."internal_errors" to "anon";

grant references on table "public"."internal_errors" to "anon";

grant select on table "public"."internal_errors" to "anon";

grant trigger on table "public"."internal_errors" to "anon";

grant truncate on table "public"."internal_errors" to "anon";

grant update on table "public"."internal_errors" to "anon";

grant delete on table "public"."internal_errors" to "authenticated";

grant insert on table "public"."internal_errors" to "authenticated";

grant references on table "public"."internal_errors" to "authenticated";

grant select on table "public"."internal_errors" to "authenticated";

grant trigger on table "public"."internal_errors" to "authenticated";

grant truncate on table "public"."internal_errors" to "authenticated";

grant update on table "public"."internal_errors" to "authenticated";

grant delete on table "public"."internal_errors" to "service_role";

grant insert on table "public"."internal_errors" to "service_role";

grant references on table "public"."internal_errors" to "service_role";

grant select on table "public"."internal_errors" to "service_role";

grant trigger on table "public"."internal_errors" to "service_role";

grant truncate on table "public"."internal_errors" to "service_role";

grant update on table "public"."internal_errors" to "service_role";

grant delete on table "public"."kiosk" to "anon";

grant insert on table "public"."kiosk" to "anon";

grant references on table "public"."kiosk" to "anon";

grant select on table "public"."kiosk" to "anon";

grant trigger on table "public"."kiosk" to "anon";

grant truncate on table "public"."kiosk" to "anon";

grant update on table "public"."kiosk" to "anon";

grant delete on table "public"."kiosk" to "authenticated";

grant insert on table "public"."kiosk" to "authenticated";

grant references on table "public"."kiosk" to "authenticated";

grant select on table "public"."kiosk" to "authenticated";

grant trigger on table "public"."kiosk" to "authenticated";

grant truncate on table "public"."kiosk" to "authenticated";

grant update on table "public"."kiosk" to "authenticated";

grant delete on table "public"."kiosk" to "service_role";

grant insert on table "public"."kiosk" to "service_role";

grant references on table "public"."kiosk" to "service_role";

grant select on table "public"."kiosk" to "service_role";

grant trigger on table "public"."kiosk" to "service_role";

grant truncate on table "public"."kiosk" to "service_role";

grant update on table "public"."kiosk" to "service_role";

grant delete on table "public"."links" to "anon";

grant insert on table "public"."links" to "anon";

grant references on table "public"."links" to "anon";

grant select on table "public"."links" to "anon";

grant trigger on table "public"."links" to "anon";

grant truncate on table "public"."links" to "anon";

grant update on table "public"."links" to "anon";

grant delete on table "public"."links" to "authenticated";

grant insert on table "public"."links" to "authenticated";

grant references on table "public"."links" to "authenticated";

grant select on table "public"."links" to "authenticated";

grant trigger on table "public"."links" to "authenticated";

grant truncate on table "public"."links" to "authenticated";

grant update on table "public"."links" to "authenticated";

grant delete on table "public"."links" to "service_role";

grant insert on table "public"."links" to "service_role";

grant references on table "public"."links" to "service_role";

grant select on table "public"."links" to "service_role";

grant trigger on table "public"."links" to "service_role";

grant truncate on table "public"."links" to "service_role";

grant update on table "public"."links" to "service_role";

grant delete on table "public"."orders" to "anon";

grant insert on table "public"."orders" to "anon";

grant references on table "public"."orders" to "anon";

grant select on table "public"."orders" to "anon";

grant trigger on table "public"."orders" to "anon";

grant truncate on table "public"."orders" to "anon";

grant update on table "public"."orders" to "anon";

grant delete on table "public"."orders" to "authenticated";

grant insert on table "public"."orders" to "authenticated";

grant references on table "public"."orders" to "authenticated";

grant select on table "public"."orders" to "authenticated";

grant trigger on table "public"."orders" to "authenticated";

grant truncate on table "public"."orders" to "authenticated";

grant update on table "public"."orders" to "authenticated";

grant delete on table "public"."orders" to "service_role";

grant insert on table "public"."orders" to "service_role";

grant references on table "public"."orders" to "service_role";

grant select on table "public"."orders" to "service_role";

grant trigger on table "public"."orders" to "service_role";

grant truncate on table "public"."orders" to "service_role";

grant update on table "public"."orders" to "service_role";

grant delete on table "public"."orders2" to "anon";

grant insert on table "public"."orders2" to "anon";

grant references on table "public"."orders2" to "anon";

grant select on table "public"."orders2" to "anon";

grant trigger on table "public"."orders2" to "anon";

grant truncate on table "public"."orders2" to "anon";

grant update on table "public"."orders2" to "anon";

grant delete on table "public"."orders2" to "authenticated";

grant insert on table "public"."orders2" to "authenticated";

grant references on table "public"."orders2" to "authenticated";

grant select on table "public"."orders2" to "authenticated";

grant trigger on table "public"."orders2" to "authenticated";

grant truncate on table "public"."orders2" to "authenticated";

grant update on table "public"."orders2" to "authenticated";

grant delete on table "public"."orders2" to "service_role";

grant insert on table "public"."orders2" to "service_role";

grant references on table "public"."orders2" to "service_role";

grant select on table "public"."orders2" to "service_role";

grant trigger on table "public"."orders2" to "service_role";

grant truncate on table "public"."orders2" to "service_role";

grant update on table "public"."orders2" to "service_role";

grant delete on table "public"."ordersTest" to "anon";

grant insert on table "public"."ordersTest" to "anon";

grant references on table "public"."ordersTest" to "anon";

grant select on table "public"."ordersTest" to "anon";

grant trigger on table "public"."ordersTest" to "anon";

grant truncate on table "public"."ordersTest" to "anon";

grant update on table "public"."ordersTest" to "anon";

grant delete on table "public"."ordersTest" to "authenticated";

grant insert on table "public"."ordersTest" to "authenticated";

grant references on table "public"."ordersTest" to "authenticated";

grant select on table "public"."ordersTest" to "authenticated";

grant trigger on table "public"."ordersTest" to "authenticated";

grant truncate on table "public"."ordersTest" to "authenticated";

grant update on table "public"."ordersTest" to "authenticated";

grant delete on table "public"."ordersTest" to "service_role";

grant insert on table "public"."ordersTest" to "service_role";

grant references on table "public"."ordersTest" to "service_role";

grant select on table "public"."ordersTest" to "service_role";

grant trigger on table "public"."ordersTest" to "service_role";

grant truncate on table "public"."ordersTest" to "service_role";

grant update on table "public"."ordersTest" to "service_role";

grant delete on table "public"."print_jobs" to "anon";

grant insert on table "public"."print_jobs" to "anon";

grant references on table "public"."print_jobs" to "anon";

grant select on table "public"."print_jobs" to "anon";

grant trigger on table "public"."print_jobs" to "anon";

grant truncate on table "public"."print_jobs" to "anon";

grant update on table "public"."print_jobs" to "anon";

grant delete on table "public"."print_jobs" to "authenticated";

grant insert on table "public"."print_jobs" to "authenticated";

grant references on table "public"."print_jobs" to "authenticated";

grant select on table "public"."print_jobs" to "authenticated";

grant trigger on table "public"."print_jobs" to "authenticated";

grant truncate on table "public"."print_jobs" to "authenticated";

grant update on table "public"."print_jobs" to "authenticated";

grant delete on table "public"."print_jobs" to "service_role";

grant insert on table "public"."print_jobs" to "service_role";

grant references on table "public"."print_jobs" to "service_role";

grant select on table "public"."print_jobs" to "service_role";

grant trigger on table "public"."print_jobs" to "service_role";

grant truncate on table "public"."print_jobs" to "service_role";

grant update on table "public"."print_jobs" to "service_role";

grant delete on table "public"."products" to "anon";

grant insert on table "public"."products" to "anon";

grant references on table "public"."products" to "anon";

grant select on table "public"."products" to "anon";

grant trigger on table "public"."products" to "anon";

grant truncate on table "public"."products" to "anon";

grant update on table "public"."products" to "anon";

grant delete on table "public"."products" to "authenticated";

grant insert on table "public"."products" to "authenticated";

grant references on table "public"."products" to "authenticated";

grant select on table "public"."products" to "authenticated";

grant trigger on table "public"."products" to "authenticated";

grant truncate on table "public"."products" to "authenticated";

grant update on table "public"."products" to "authenticated";

grant delete on table "public"."products" to "service_role";

grant insert on table "public"."products" to "service_role";

grant references on table "public"."products" to "service_role";

grant select on table "public"."products" to "service_role";

grant trigger on table "public"."products" to "service_role";

grant truncate on table "public"."products" to "service_role";

grant update on table "public"."products" to "service_role";

grant delete on table "public"."refund_queue" to "anon";

grant insert on table "public"."refund_queue" to "anon";

grant references on table "public"."refund_queue" to "anon";

grant select on table "public"."refund_queue" to "anon";

grant trigger on table "public"."refund_queue" to "anon";

grant truncate on table "public"."refund_queue" to "anon";

grant update on table "public"."refund_queue" to "anon";

grant delete on table "public"."refund_queue" to "authenticated";

grant insert on table "public"."refund_queue" to "authenticated";

grant references on table "public"."refund_queue" to "authenticated";

grant select on table "public"."refund_queue" to "authenticated";

grant trigger on table "public"."refund_queue" to "authenticated";

grant truncate on table "public"."refund_queue" to "authenticated";

grant update on table "public"."refund_queue" to "authenticated";

grant delete on table "public"."refund_queue" to "service_role";

grant insert on table "public"."refund_queue" to "service_role";

grant references on table "public"."refund_queue" to "service_role";

grant select on table "public"."refund_queue" to "service_role";

grant trigger on table "public"."refund_queue" to "service_role";

grant truncate on table "public"."refund_queue" to "service_role";

grant update on table "public"."refund_queue" to "service_role";

grant delete on table "public"."service_categories" to "anon";

grant insert on table "public"."service_categories" to "anon";

grant references on table "public"."service_categories" to "anon";

grant select on table "public"."service_categories" to "anon";

grant trigger on table "public"."service_categories" to "anon";

grant truncate on table "public"."service_categories" to "anon";

grant update on table "public"."service_categories" to "anon";

grant delete on table "public"."service_categories" to "authenticated";

grant insert on table "public"."service_categories" to "authenticated";

grant references on table "public"."service_categories" to "authenticated";

grant select on table "public"."service_categories" to "authenticated";

grant trigger on table "public"."service_categories" to "authenticated";

grant truncate on table "public"."service_categories" to "authenticated";

grant update on table "public"."service_categories" to "authenticated";

grant delete on table "public"."service_categories" to "service_role";

grant insert on table "public"."service_categories" to "service_role";

grant references on table "public"."service_categories" to "service_role";

grant select on table "public"."service_categories" to "service_role";

grant trigger on table "public"."service_categories" to "service_role";

grant truncate on table "public"."service_categories" to "service_role";

grant update on table "public"."service_categories" to "service_role";

grant delete on table "public"."services" to "anon";

grant insert on table "public"."services" to "anon";

grant references on table "public"."services" to "anon";

grant select on table "public"."services" to "anon";

grant trigger on table "public"."services" to "anon";

grant truncate on table "public"."services" to "anon";

grant update on table "public"."services" to "anon";

grant delete on table "public"."services" to "authenticated";

grant insert on table "public"."services" to "authenticated";

grant references on table "public"."services" to "authenticated";

grant select on table "public"."services" to "authenticated";

grant trigger on table "public"."services" to "authenticated";

grant truncate on table "public"."services" to "authenticated";

grant update on table "public"."services" to "authenticated";

grant delete on table "public"."services" to "service_role";

grant insert on table "public"."services" to "service_role";

grant references on table "public"."services" to "service_role";

grant select on table "public"."services" to "service_role";

grant trigger on table "public"."services" to "service_role";

grant truncate on table "public"."services" to "service_role";

grant update on table "public"."services" to "service_role";

grant delete on table "public"."settings" to "anon";

grant insert on table "public"."settings" to "anon";

grant references on table "public"."settings" to "anon";

grant select on table "public"."settings" to "anon";

grant trigger on table "public"."settings" to "anon";

grant truncate on table "public"."settings" to "anon";

grant update on table "public"."settings" to "anon";

grant delete on table "public"."settings" to "authenticated";

grant insert on table "public"."settings" to "authenticated";

grant references on table "public"."settings" to "authenticated";

grant select on table "public"."settings" to "authenticated";

grant trigger on table "public"."settings" to "authenticated";

grant truncate on table "public"."settings" to "authenticated";

grant update on table "public"."settings" to "authenticated";

grant delete on table "public"."settings" to "service_role";

grant insert on table "public"."settings" to "service_role";

grant references on table "public"."settings" to "service_role";

grant select on table "public"."settings" to "service_role";

grant trigger on table "public"."settings" to "service_role";

grant truncate on table "public"."settings" to "service_role";

grant update on table "public"."settings" to "service_role";

grant delete on table "public"."shipping_package_profiles" to "anon";

grant insert on table "public"."shipping_package_profiles" to "anon";

grant references on table "public"."shipping_package_profiles" to "anon";

grant select on table "public"."shipping_package_profiles" to "anon";

grant trigger on table "public"."shipping_package_profiles" to "anon";

grant truncate on table "public"."shipping_package_profiles" to "anon";

grant update on table "public"."shipping_package_profiles" to "anon";

grant delete on table "public"."shipping_package_profiles" to "authenticated";

grant insert on table "public"."shipping_package_profiles" to "authenticated";

grant references on table "public"."shipping_package_profiles" to "authenticated";

grant select on table "public"."shipping_package_profiles" to "authenticated";

grant trigger on table "public"."shipping_package_profiles" to "authenticated";

grant truncate on table "public"."shipping_package_profiles" to "authenticated";

grant update on table "public"."shipping_package_profiles" to "authenticated";

grant delete on table "public"."shipping_package_profiles" to "service_role";

grant insert on table "public"."shipping_package_profiles" to "service_role";

grant references on table "public"."shipping_package_profiles" to "service_role";

grant select on table "public"."shipping_package_profiles" to "service_role";

grant trigger on table "public"."shipping_package_profiles" to "service_role";

grant truncate on table "public"."shipping_package_profiles" to "service_role";

grant update on table "public"."shipping_package_profiles" to "service_role";

grant delete on table "public"."shop" to "anon";

grant insert on table "public"."shop" to "anon";

grant references on table "public"."shop" to "anon";

grant select on table "public"."shop" to "anon";

grant trigger on table "public"."shop" to "anon";

grant truncate on table "public"."shop" to "anon";

grant update on table "public"."shop" to "anon";

grant delete on table "public"."shop" to "authenticated";

grant insert on table "public"."shop" to "authenticated";

grant references on table "public"."shop" to "authenticated";

grant select on table "public"."shop" to "authenticated";

grant trigger on table "public"."shop" to "authenticated";

grant truncate on table "public"."shop" to "authenticated";

grant update on table "public"."shop" to "authenticated";

grant delete on table "public"."shop" to "service_role";

grant insert on table "public"."shop" to "service_role";

grant references on table "public"."shop" to "service_role";

grant select on table "public"."shop" to "service_role";

grant trigger on table "public"."shop" to "service_role";

grant truncate on table "public"."shop" to "service_role";

grant update on table "public"."shop" to "service_role";

grant delete on table "public"."webhook_queue" to "anon";

grant insert on table "public"."webhook_queue" to "anon";

grant references on table "public"."webhook_queue" to "anon";

grant select on table "public"."webhook_queue" to "anon";

grant trigger on table "public"."webhook_queue" to "anon";

grant truncate on table "public"."webhook_queue" to "anon";

grant update on table "public"."webhook_queue" to "anon";

grant delete on table "public"."webhook_queue" to "authenticated";

grant insert on table "public"."webhook_queue" to "authenticated";

grant references on table "public"."webhook_queue" to "authenticated";

grant select on table "public"."webhook_queue" to "authenticated";

grant trigger on table "public"."webhook_queue" to "authenticated";

grant truncate on table "public"."webhook_queue" to "authenticated";

grant update on table "public"."webhook_queue" to "authenticated";

grant delete on table "public"."webhook_queue" to "service_role";

grant insert on table "public"."webhook_queue" to "service_role";

grant references on table "public"."webhook_queue" to "service_role";

grant select on table "public"."webhook_queue" to "service_role";

grant trigger on table "public"."webhook_queue" to "service_role";

grant truncate on table "public"."webhook_queue" to "service_role";

grant update on table "public"."webhook_queue" to "service_role";


  create policy "booking_holds_insert_own"
  on "public"."booking_holds"
  as permissive
  for insert
  to public
with check ((EXISTS ( SELECT 1
   FROM public.bookings b
  WHERE ((b.id = booking_holds.booking_id) AND (b.user_id = auth.uid())))));



  create policy "booking_holds_select_own"
  on "public"."booking_holds"
  as permissive
  for select
  to public
using ((EXISTS ( SELECT 1
   FROM public.bookings b
  WHERE ((b.id = booking_holds.booking_id) AND (b.user_id = auth.uid())))));



  create policy "bookings_insert_own"
  on "public"."bookings"
  as permissive
  for insert
  to public
with check (((auth.uid() = user_id) AND (status = 'requested'::text)));



  create policy "bookings_select_own"
  on "public"."bookings"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "bookings_update_own_cancel"
  on "public"."bookings"
  as permissive
  for update
  to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "cart_items_owner_delete"
  on "public"."cart_items"
  as permissive
  for delete
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.cart_sessions s
  WHERE ((s.id = cart_items.cart_id) AND (s.user_id = auth.uid())))));



  create policy "cart_items_owner_insert"
  on "public"."cart_items"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM public.cart_sessions s
  WHERE ((s.id = cart_items.cart_id) AND (s.user_id = auth.uid())))));



  create policy "cart_items_owner_select"
  on "public"."cart_items"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.cart_sessions s
  WHERE ((s.id = cart_items.cart_id) AND (s.user_id = auth.uid())))));



  create policy "cart_items_owner_update"
  on "public"."cart_items"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.cart_sessions s
  WHERE ((s.id = cart_items.cart_id) AND (s.user_id = auth.uid())))))
with check ((EXISTS ( SELECT 1
   FROM public.cart_sessions s
  WHERE ((s.id = cart_items.cart_id) AND (s.user_id = auth.uid())))));



  create policy "cart_sessions_owner_delete"
  on "public"."cart_sessions"
  as permissive
  for delete
  to authenticated
using ((user_id = auth.uid()));



  create policy "cart_sessions_owner_insert"
  on "public"."cart_sessions"
  as permissive
  for insert
  to authenticated
with check ((user_id = auth.uid()));



  create policy "cart_sessions_owner_select"
  on "public"."cart_sessions"
  as permissive
  for select
  to authenticated
using ((user_id = auth.uid()));



  create policy "cart_sessions_owner_update"
  on "public"."cart_sessions"
  as permissive
  for update
  to authenticated
using ((user_id = auth.uid()))
with check ((user_id = auth.uid()));



  create policy "carts_owner_delete"
  on "public"."carts"
  as permissive
  for delete
  to authenticated
using ((user_id = auth.uid()));



  create policy "carts_owner_insert"
  on "public"."carts"
  as permissive
  for insert
  to authenticated
with check ((user_id = auth.uid()));



  create policy "carts_owner_select"
  on "public"."carts"
  as permissive
  for select
  to authenticated
using ((user_id = auth.uid()));



  create policy "carts_owner_update"
  on "public"."carts"
  as permissive
  for update
  to authenticated
using ((user_id = auth.uid()))
with check ((user_id = auth.uid()));



  create policy "credits_ledger_select_own"
  on "public"."credits_ledger"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Customers: User can insert their own record"
  on "public"."customers"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Customers: User can select their record"
  on "public"."customers"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Customers: User can update their record"
  on "public"."customers"
  as permissive
  for update
  to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "admins can read customers"
  on "public"."customers"
  as permissive
  for all
  to public
using ((((auth.jwt() -> 'user_metadata'::text) ->> 'role'::text) = 'admin'::text))
with check ((((auth.jwt() -> 'user_metadata'::text) ->> 'role'::text) = 'admin'::text));



  create policy "customers_insert_own"
  on "public"."customers"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "customers_select_own"
  on "public"."customers"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "customers_update_own"
  on "public"."customers"
  as permissive
  for update
  to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "external_calendar_events: admin all"
  on "public"."external_calendar_events"
  as permissive
  for all
  to public
using (public.is_admin())
with check (public.is_admin());



  create policy "Enable insert for authenticated users only"
  on "public"."kiosk"
  as permissive
  for insert
  to authenticated, service_role, supabase_admin
with check (true);



  create policy "Enable read access for all users"
  on "public"."kiosk"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update for users based on email"
  on "public"."kiosk"
  as permissive
  for update
  to authenticated, supabase_admin, service_role
using (true)
with check (true);



  create policy "memberships_insert_pending_own"
  on "public"."memberships"
  as permissive
  for insert
  to public
with check (((auth.uid() = user_id) AND (status = 'pending_checkout'::public.membership_status)));



  create policy "memberships_select_own"
  on "public"."memberships"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Admin full access"
  on "public"."orders2"
  as permissive
  for all
  to public
using ((((auth.jwt() -> 'user_metadata'::text) ->> 'role'::text) = 'admin'::text))
with check ((((auth.jwt() -> 'user_metadata'::text) ->> 'role'::text) = 'admin'::text));



  create policy "Users can view their own orders"
  on "public"."orders2"
  as permissive
  for select
  to public
using (((auth.role() = 'authenticated'::text) AND (user_id = auth.uid())));



  create policy "Admin full access"
  on "public"."service_categories"
  as permissive
  for all
  to public
using ((((auth.jwt() -> 'user_metadata'::text) ->> 'role'::text) = 'admin'::text))
with check ((((auth.jwt() -> 'user_metadata'::text) ->> 'role'::text) = 'admin'::text));



  create policy "Enable read access for all users"
  on "public"."services"
  as permissive
  for select
  to authenticated, service_role, supabase_admin, anon
using (true);



  create policy "Enable update for users"
  on "public"."services"
  as permissive
  for update
  to authenticated, supabase_admin, service_role
using (true)
with check (true);



  create policy "Insert"
  on "public"."services"
  as permissive
  for insert
  to authenticated, supabase_admin, service_role
with check (true);



  create policy "Enable read access for all users"
  on "public"."settings"
  as permissive
  for select
  to public
using (true);



  create policy "system_config: admin write"
  on "public"."system_config"
  as permissive
  for all
  to public
using (public.is_admin());



  create policy "system_config: public read"
  on "public"."system_config"
  as permissive
  for select
  to public
using (true);


CREATE TRIGGER update_cart_sessions_updated_at BEFORE UPDATE ON public.cart_sessions FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_cart_timestamp BEFORE UPDATE ON public.cart_sessions FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_cart_timestamp BEFORE UPDATE ON public.carts FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER set_user_id_before_insert BEFORE INSERT ON public.customers FOR EACH ROW EXECUTE FUNCTION public.set_user_id();
ALTER TABLE "public"."customers" DISABLE TRIGGER "set_user_id_before_insert";

CREATE TRIGGER trg_external_calendar_events_updated_at BEFORE UPDATE ON public.external_calendar_events FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_queue_print_job AFTER INSERT OR UPDATE OF state, "customerId", "isServiceOrder" ON public.orders2 FOR EACH ROW EXECUTE FUNCTION public.queue_print_job_on_order_completed();

CREATE TRIGGER trg_refund_queue_updated_at BEFORE UPDATE ON public.refund_queue FOR EACH ROW EXECUTE FUNCTION public.update_refund_queue_updated_at();

CREATE TRIGGER trg_touch_shipping_package_profiles_updated_at BEFORE UPDATE ON public.shipping_package_profiles FOR EACH ROW EXECUTE FUNCTION public.touch_shipping_package_profiles_updated_at();


  create policy "Public can read foprinter updates"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'foprinter'::text));



