-- Unified activity logging, unread cursors, and staff account linking.
-- Supports dashboard notifications/history from durable DB events.

CREATE TABLE IF NOT EXISTS public.activity_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  entity_type text NOT NULL CHECK (entity_type IN ('order', 'ticket', 'customer', 'staff', 'system')),
  entity_id text NOT NULL,
  action text NOT NULL,
  scope text NOT NULL DEFAULT 'all' CHECK (scope IN ('all', 'tickets', 'orders', 'customers')),
  summary text NOT NULL DEFAULT '',
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  actor_type text NOT NULL DEFAULT 'system' CHECK (actor_type IN ('user', 'system', 'integration')),
  actor_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  actor_role text,
  actor_service text,
  order_db_id bigint REFERENCES public.orders2(id) ON DELETE SET NULL,
  ticket_id uuid REFERENCES public.internal_errors(id) ON DELETE SET NULL,
  customer_id uuid REFERENCES public.customers(id) ON DELETE SET NULL,
  location_id text,
  dedupe_key text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS activity_events_dedupe_key_unique
  ON public.activity_events (dedupe_key)
  WHERE dedupe_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS activity_events_scope_occurred_idx
  ON public.activity_events (scope, occurred_at DESC);

CREATE INDEX IF NOT EXISTS activity_events_entity_occurred_idx
  ON public.activity_events (entity_type, entity_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS activity_events_order_occurred_idx
  ON public.activity_events (order_db_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS activity_events_ticket_occurred_idx
  ON public.activity_events (ticket_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS activity_events_customer_occurred_idx
  ON public.activity_events (customer_id, occurred_at DESC);

CREATE TABLE IF NOT EXISTS public.activity_read_cursors (
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  scope text NOT NULL CHECK (scope IN ('all', 'tickets', 'orders', 'customers')),
  last_read_at timestamptz NOT NULL DEFAULT 'epoch'::timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, scope)
);

CREATE INDEX IF NOT EXISTS activity_read_cursors_scope_last_read_idx
  ON public.activity_read_cursors (scope, last_read_at DESC);

CREATE TABLE IF NOT EXISTS public.staff_account_links (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  auth_user_id uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  square_team_member_id text NOT NULL UNIQUE,
  normalized_email text NOT NULL,
  square_status text,
  square_assigned_locations jsonb NOT NULL DEFAULT '[]'::jsonb,
  square_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  sync_state text NOT NULL DEFAULT 'linked' CHECK (sync_state IN ('linked', 'pending', 'error')),
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS staff_account_links_email_idx
  ON public.staff_account_links (normalized_email);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger
    WHERE tgname = 'trg_activity_read_cursors_updated_at'
  ) THEN
    CREATE TRIGGER trg_activity_read_cursors_updated_at
      BEFORE UPDATE ON public.activity_read_cursors
      FOR EACH ROW
      EXECUTE FUNCTION public.set_updated_at();
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger
    WHERE tgname = 'trg_staff_account_links_updated_at'
  ) THEN
    CREATE TRIGGER trg_staff_account_links_updated_at
      BEFORE UPDATE ON public.staff_account_links
      FOR EACH ROW
      EXECUTE FUNCTION public.set_updated_at();
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.resolve_order_db_id(
  p_ss_order_id bigint,
  p_square_order_id text
)
RETURNS bigint
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  v_order_id bigint;
BEGIN
  IF p_ss_order_id IS NOT NULL THEN
    SELECT o.id
      INTO v_order_id
      FROM public.orders2 o
      WHERE o.id = p_ss_order_id
      LIMIT 1;

    IF v_order_id IS NOT NULL THEN
      RETURN v_order_id;
    END IF;
  END IF;

  IF p_square_order_id IS NOT NULL AND length(btrim(p_square_order_id)) > 0 THEN
    SELECT o.id
      INTO v_order_id
      FROM public.orders2 o
      WHERE o."orderId" = p_square_order_id
      ORDER BY o.created DESC
      LIMIT 1;
  END IF;

  RETURN v_order_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.record_activity_event(
  p_entity_type text,
  p_entity_id text,
  p_action text,
  p_scope text DEFAULT 'all',
  p_summary text DEFAULT '',
  p_details jsonb DEFAULT '{}'::jsonb,
  p_actor_type text DEFAULT 'system',
  p_actor_user_id uuid DEFAULT NULL,
  p_actor_role text DEFAULT NULL,
  p_actor_service text DEFAULT NULL,
  p_order_db_id bigint DEFAULT NULL,
  p_ticket_id uuid DEFAULT NULL,
  p_customer_id uuid DEFAULT NULL,
  p_location_id text DEFAULT NULL,
  p_dedupe_key text DEFAULT NULL,
  p_occurred_at timestamptz DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id bigint;
BEGIN
  INSERT INTO public.activity_events (
    occurred_at,
    entity_type,
    entity_id,
    action,
    scope,
    summary,
    details,
    actor_type,
    actor_user_id,
    actor_role,
    actor_service,
    order_db_id,
    ticket_id,
    customer_id,
    location_id,
    dedupe_key
  )
  VALUES (
    COALESCE(p_occurred_at, now()),
    p_entity_type,
    p_entity_id,
    p_action,
    p_scope,
    COALESCE(p_summary, ''),
    COALESCE(p_details, '{}'::jsonb),
    COALESCE(p_actor_type, 'system'),
    p_actor_user_id,
    p_actor_role,
    p_actor_service,
    p_order_db_id,
    p_ticket_id,
    p_customer_id,
    p_location_id,
    p_dedupe_key
  )
  ON CONFLICT (dedupe_key) DO NOTHING
  RETURNING id INTO v_id;

  IF v_id IS NOT NULL THEN
    RETURN v_id;
  END IF;

  IF p_dedupe_key IS NOT NULL THEN
    SELECT id INTO v_id
      FROM public.activity_events
      WHERE dedupe_key = p_dedupe_key
      LIMIT 1;
  END IF;

  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.trg_links_activity_event()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_order_db_id bigint;
  v_entity_id text;
  v_action text;
  v_summary text;
  v_dedupe text;
BEGIN
  v_order_db_id := public.resolve_order_db_id(NEW."ssOrderId", NEW."orderId");
  v_entity_id := COALESCE(NEW."ssOrderId"::text, NEW."orderId", NEW.id::text);
  v_action := CASE WHEN TG_OP = 'INSERT' THEN 'order.link.created' ELSE 'order.link.updated' END;
  v_summary := CASE
    WHEN TG_OP = 'INSERT' THEN format('Download link created for order %s', v_entity_id)
    ELSE format('Download link updated for order %s', v_entity_id)
  END;
  v_dedupe := format('links:%s:%s:%s', NEW.id::text, lower(TG_OP), coalesce(NEW.expires_date::text, 'none'));

  PERFORM public.record_activity_event(
    'order',
    v_entity_id,
    v_action,
    'orders',
    v_summary,
    jsonb_build_object(
      'source_table', 'links',
      'link_id', NEW.id,
      'ssOrderId', NEW."ssOrderId",
      'orderId', NEW."orderId",
      'expires_date', NEW.expires_date,
      'email', NEW.email,
      'source', NEW.source
    ),
    'system',
    NULL,
    NULL,
    'db_trigger',
    v_order_db_id,
    NULL,
    NULL,
    NEW."locationId",
    v_dedupe,
    now()
  );

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.trg_links_archive_activity_event()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_order_db_id bigint;
  v_entity_id text;
  v_dedupe text;
BEGIN
  v_order_db_id := public.resolve_order_db_id(NEW."ssOrderId", NEW."orderId");
  v_entity_id := COALESCE(NEW."ssOrderId"::text, NEW."orderId", NEW.id::text);
  v_dedupe := format(
    'links_archive:%s:%s',
    NEW.id::text,
    coalesce(NEW.archived_at::text, now()::text)
  );

  PERFORM public.record_activity_event(
    'order',
    v_entity_id,
    'order.link.archived',
    'orders',
    format('Download link archived for order %s', v_entity_id),
    jsonb_build_object(
      'source_table', 'links_archive',
      'archive_id', NEW.id,
      'reason', NEW.reason,
      'ssOrderId', NEW."ssOrderId",
      'orderId', NEW."orderId",
      'expires_date', NEW.expires_date,
      'email', NEW.email,
      'source', NEW.source
    ),
    'system',
    NULL,
    NULL,
    'db_trigger',
    v_order_db_id,
    NULL,
    NULL,
    NULL,
    v_dedupe,
    NEW.archived_at
  );

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.trg_order_email_activity_event()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_order_id bigint;
  v_entity_id text;
  v_action text;
  v_summary text;
  v_dedupe text;
  v_should_emit boolean := true;
BEGIN
  IF TG_OP = 'UPDATE' THEN
    IF COALESCE(NEW.status, '') = COALESCE(OLD.status, '')
      AND COALESCE(NEW.last_event, '') = COALESCE(OLD.last_event, '')
      AND COALESCE(NEW.last_event_at::text, '') = COALESCE(OLD.last_event_at::text, '')
      AND COALESCE(NEW.open_count, 0) = COALESCE(OLD.open_count, 0) THEN
      v_should_emit := false;
    END IF;
  END IF;

  IF NOT v_should_emit THEN
    RETURN NEW;
  END IF;

  v_order_id := NEW.order_db_id;
  v_entity_id := COALESCE(
    NEW.order_db_id::text,
    NEW.order_number,
    NEW.square_order_id,
    NEW.tracking_id::text,
    NEW.id::text
  );

  v_action := CASE COALESCE(NEW.status, '')
    WHEN 'failed' THEN 'order.email.failed'
    WHEN 'opened' THEN 'order.email.opened'
    WHEN 'delivered' THEN 'order.email.delivered'
    WHEN 'sent' THEN 'order.email.sent'
    WHEN 'queued' THEN 'order.email.queued'
    ELSE 'order.email.updated'
  END;

  v_summary := format(
    'Order email %s %s (%s)',
    COALESCE(NEW.email_kind, 'unknown'),
    COALESCE(NEW.status, 'updated'),
    COALESCE(NEW.recipient_email, 'no-recipient')
  );

  v_dedupe := CASE
    WHEN TG_OP = 'INSERT'
      THEN format('order_email:%s:insert', NEW.id::text)
    ELSE format(
      'order_email:%s:update:%s:%s:%s',
      NEW.id::text,
      COALESCE(NEW.status, 'none'),
      COALESCE(NEW.last_event, 'none'),
      COALESCE(NEW.last_event_at::text, 'none')
    )
  END;

  PERFORM public.record_activity_event(
    'order',
    v_entity_id,
    v_action,
    'orders',
    v_summary,
    jsonb_build_object(
      'message_id', NEW.id,
      'tracking_id', NEW.tracking_id,
      'email_kind', NEW.email_kind,
      'event_type', NEW.event_type,
      'status', NEW.status,
      'sent_at', NEW.sent_at,
      'delivered_at', NEW.delivered_at,
      'opened_first_at', NEW.opened_first_at,
      'opened_last_at', NEW.opened_last_at,
      'open_count', NEW.open_count,
      'last_event', NEW.last_event,
      'last_event_at', NEW.last_event_at,
      'failure_reason', NEW.failure_reason,
      'source_service', NEW.source_service
    ),
    'integration',
    NULL,
    NULL,
    COALESCE(NEW.source_service, 'fomailer'),
    v_order_id,
    NULL,
    NULL,
    NEW.location_id,
    v_dedupe,
    COALESCE(NEW.last_event_at, NEW.created_at, now())
  );

  RETURN NEW;
END;
$$;

DO $$
BEGIN
  IF to_regclass('public.links') IS NOT NULL THEN
    DROP TRIGGER IF EXISTS trg_links_activity_event ON public.links;
    CREATE TRIGGER trg_links_activity_event
      AFTER INSERT OR UPDATE ON public.links
      FOR EACH ROW
      EXECUTE FUNCTION public.trg_links_activity_event();
  END IF;

  IF to_regclass('public.links_archive') IS NOT NULL THEN
    DROP TRIGGER IF EXISTS trg_links_archive_activity_event ON public.links_archive;
    CREATE TRIGGER trg_links_archive_activity_event
      AFTER INSERT ON public.links_archive
      FOR EACH ROW
      EXECUTE FUNCTION public.trg_links_archive_activity_event();
  END IF;

  IF to_regclass('public.order_email_messages') IS NOT NULL THEN
    DROP TRIGGER IF EXISTS trg_order_email_activity_event ON public.order_email_messages;
    CREATE TRIGGER trg_order_email_activity_event
      AFTER INSERT OR UPDATE ON public.order_email_messages
      FOR EACH ROW
      EXECUTE FUNCTION public.trg_order_email_activity_event();
  END IF;
END $$;

ALTER TABLE public.activity_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_read_cursors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_account_links ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "activity_events_staff_read" ON public.activity_events;
CREATE POLICY "activity_events_staff_read"
  ON public.activity_events
  FOR SELECT
  TO authenticated
  USING (public.is_dashboard_staff());

DROP POLICY IF EXISTS "activity_events_service_all" ON public.activity_events;
CREATE POLICY "activity_events_service_all"
  ON public.activity_events
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "activity_read_cursors_select_own_or_staff" ON public.activity_read_cursors;
CREATE POLICY "activity_read_cursors_select_own_or_staff"
  ON public.activity_read_cursors
  FOR SELECT
  TO authenticated
  USING ((auth.uid() = user_id) OR public.is_dashboard_staff());

DROP POLICY IF EXISTS "activity_read_cursors_insert_own_or_staff" ON public.activity_read_cursors;
CREATE POLICY "activity_read_cursors_insert_own_or_staff"
  ON public.activity_read_cursors
  FOR INSERT
  TO authenticated
  WITH CHECK ((auth.uid() = user_id) OR public.is_dashboard_staff());

DROP POLICY IF EXISTS "activity_read_cursors_update_own_or_staff" ON public.activity_read_cursors;
CREATE POLICY "activity_read_cursors_update_own_or_staff"
  ON public.activity_read_cursors
  FOR UPDATE
  TO authenticated
  USING ((auth.uid() = user_id) OR public.is_dashboard_staff())
  WITH CHECK ((auth.uid() = user_id) OR public.is_dashboard_staff());

DROP POLICY IF EXISTS "activity_read_cursors_service_all" ON public.activity_read_cursors;
CREATE POLICY "activity_read_cursors_service_all"
  ON public.activity_read_cursors
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "staff_account_links_admin_all" ON public.staff_account_links;
CREATE POLICY "staff_account_links_admin_all"
  ON public.staff_account_links
  FOR ALL
  TO authenticated
  USING (public.has_app_role(ARRAY['admin', 'service']::text[]))
  WITH CHECK (public.has_app_role(ARRAY['admin', 'service']::text[]));

DROP POLICY IF EXISTS "staff_account_links_service_all" ON public.staff_account_links;
CREATE POLICY "staff_account_links_service_all"
  ON public.staff_account_links
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- One-time last-90-days activity backfill.
WITH cutoff AS (
  SELECT now() - interval '90 days' AS value
)
INSERT INTO public.activity_events (
  occurred_at,
  entity_type,
  entity_id,
  action,
  scope,
  summary,
  details,
  actor_type,
  actor_user_id,
  actor_role,
  actor_service,
  order_db_id,
  ticket_id,
  customer_id,
  location_id,
  dedupe_key
)
SELECT
  o.created,
  'order',
  o.id::text,
  'order.created',
  'orders',
  format('Order %s created', o.id::text),
  jsonb_build_object(
    'state', o.state,
    'isServiceOrder', o."isServiceOrder",
    'orderId', o."orderId",
    'ssOrderId', o."ssOrderId"
  ),
  CASE WHEN o.user_id IS NOT NULL THEN 'user' ELSE 'integration' END,
  o.user_id,
  NULL,
  'backfill',
  o.id,
  NULL,
  NULL,
  o."locationId",
  format('backfill:orders2:created:%s', o.id::text)
FROM public.orders2 o, cutoff
WHERE o.created >= cutoff.value
ON CONFLICT (dedupe_key) DO NOTHING;

WITH cutoff AS (
  SELECT now() - interval '90 days' AS value
)
INSERT INTO public.activity_events (
  occurred_at,
  entity_type,
  entity_id,
  action,
  scope,
  summary,
  details,
  actor_type,
  actor_user_id,
  actor_service,
  order_db_id,
  location_id,
  dedupe_key
)
SELECT
  COALESCE(m.last_event_at, m.created_at, now()),
  'order',
  COALESCE(m.order_db_id::text, m.order_number, m.square_order_id, m.id::text),
  format('order.email.%s', COALESCE(m.status, 'updated')),
  'orders',
  format('Order email %s %s (%s)', COALESCE(m.email_kind, 'unknown'), COALESCE(m.status, 'updated'), COALESCE(m.recipient_email, 'no-recipient')),
  jsonb_build_object(
    'message_id', m.id,
    'tracking_id', m.tracking_id,
    'email_kind', m.email_kind,
    'status', m.status,
    'sent_at', m.sent_at,
    'delivered_at', m.delivered_at,
    'opened_first_at', m.opened_first_at,
    'opened_last_at', m.opened_last_at,
    'open_count', m.open_count,
    'last_event', m.last_event,
    'failure_reason', m.failure_reason
  ),
  'integration',
  NULL,
  COALESCE(m.source_service, 'backfill'),
  m.order_db_id,
  m.location_id,
  format('backfill:order_email_messages:%s', m.id::text)
FROM public.order_email_messages m, cutoff
WHERE COALESCE(m.last_event_at, m.created_at, now()) >= cutoff.value
ON CONFLICT (dedupe_key) DO NOTHING;

WITH cutoff AS (
  SELECT now() - interval '90 days' AS value
)
INSERT INTO public.activity_events (
  occurred_at,
  entity_type,
  entity_id,
  action,
  scope,
  summary,
  details,
  actor_type,
  actor_user_id,
  actor_service,
  order_db_id,
  dedupe_key
)
SELECT
  rq.created_at,
  'order',
  rq.order_db_id::text,
  format('order.refund.%s', rq.status),
  'orders',
  format('Refund %s for order %s', rq.status, rq.order_db_id::text),
  jsonb_build_object(
    'refund_id', rq.id,
    'amount', rq.amount,
    'reason', rq.reason,
    'status', rq.status,
    'square_refund_id', rq.square_refund_id,
    'error_message', rq.error_message
  ),
  'user',
  rq.initiated_by,
  'backfill',
  rq.order_db_id,
  format('backfill:refund_queue:%s', rq.id::text)
FROM public.refund_queue rq, cutoff
WHERE rq.created_at >= cutoff.value
ON CONFLICT (dedupe_key) DO NOTHING;

WITH cutoff AS (
  SELECT now() - interval '90 days' AS value
)
INSERT INTO public.activity_events (
  occurred_at,
  entity_type,
  entity_id,
  action,
  scope,
  summary,
  details,
  actor_type,
  actor_user_id,
  actor_service,
  ticket_id,
  dedupe_key
)
SELECT
  ie.timestamp,
  'ticket',
  ie.id::text,
  CASE WHEN ie.is_resolved THEN 'ticket.resolved' ELSE 'ticket.created' END,
  'tickets',
  CASE WHEN ie.is_resolved THEN format('Ticket resolved: %s', ie.message) ELSE format('Ticket created: %s', ie.message) END,
  jsonb_build_object(
    'level', ie.level,
    'file', ie.file,
    'message', ie.message,
    'is_resolved', ie.is_resolved,
    'resolved_at', ie.resolved_at
  ),
  CASE WHEN ie.user_id IS NOT NULL THEN 'user' ELSE 'system' END,
  ie.user_id,
  'backfill',
  ie.id,
  format('backfill:internal_errors:%s', ie.id::text)
FROM public.internal_errors ie, cutoff
WHERE ie.file = 'dashboard-ticket'
  AND ie.timestamp >= cutoff.value
ON CONFLICT (dedupe_key) DO NOTHING;

WITH cutoff AS (
  SELECT now() - interval '90 days' AS value
)
INSERT INTO public.activity_events (
  occurred_at,
  entity_type,
  entity_id,
  action,
  scope,
  summary,
  details,
  actor_type,
  actor_service,
  order_db_id,
  location_id,
  dedupe_key
)
SELECT
  pj.created_at,
  'order',
  pj.order_id::text,
  format('order.print.%s', COALESCE(pj.status, 'queued')),
  'orders',
  format('Print job %s for order %s', COALESCE(pj.status, 'queued'), pj.order_id::text),
  jsonb_build_object(
    'print_job_id', pj.id,
    'job_type', pj.job_type,
    'status', pj.status,
    'attempts', pj.attempts,
    'claimed_by', pj.claimed_by,
    'last_error', pj.last_error
  ),
  'integration',
  'backfill',
  pj.order_id,
  pj.location_id,
  format('backfill:print_jobs:%s', pj.id::text)
FROM public.print_jobs pj, cutoff
WHERE pj.created_at >= cutoff.value
ON CONFLICT (dedupe_key) DO NOTHING;

DO $$
BEGIN
  IF to_regclass('public.links_archive') IS NULL THEN
    RETURN;
  END IF;

  WITH cutoff AS (
    SELECT now() - interval '90 days' AS value
  )
  INSERT INTO public.activity_events (
    occurred_at,
    entity_type,
    entity_id,
    action,
    scope,
    summary,
    details,
    actor_type,
    actor_service,
    order_db_id,
    dedupe_key
  )
  SELECT
    la.archived_at,
    'order',
    COALESCE(la."ssOrderId"::text, la."orderId", la.id::text),
    'order.link.archived',
    'orders',
    format('Archived download link for order %s', COALESCE(la."ssOrderId"::text, la."orderId", la.id::text)),
    jsonb_build_object(
      'archive_id', la.id,
      'reason', la.reason,
      'ssOrderId', la."ssOrderId",
      'orderId', la."orderId",
      'expires_date', la.expires_date,
      'source', la.source
    ),
    'system',
    'backfill',
    public.resolve_order_db_id(la."ssOrderId", la."orderId"),
    format('backfill:links_archive:%s', la.id::text)
  FROM public.links_archive la, cutoff
  WHERE la.archived_at >= cutoff.value
  ON CONFLICT (dedupe_key) DO NOTHING;
END $$;
