-- =============================================================================
-- Member waiver workflow
-- - Versioned waiver templates
-- - Member signatures with 1-year expiry
-- - Helper function to resolve current waiver status
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.waiver_templates (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  version       bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  title         text NOT NULL,
  body          text NOT NULL,
  metadata      jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active     boolean NOT NULL DEFAULT false,
  created_by    uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  published_by  uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  published_at  timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT waiver_templates_body_not_blank CHECK (length(trim(body)) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS waiver_templates_single_active_idx
  ON public.waiver_templates (is_active)
  WHERE is_active = true;

CREATE INDEX IF NOT EXISTS waiver_templates_active_lookup_idx
  ON public.waiver_templates (published_at DESC NULLS LAST, created_at DESC)
  WHERE is_active = true;

CREATE INDEX IF NOT EXISTS waiver_templates_created_at_idx
  ON public.waiver_templates (created_at DESC);

CREATE TABLE IF NOT EXISTS public.member_waiver_signatures (
  id                        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                   uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  customer_id               uuid REFERENCES public.customers(id) ON DELETE SET NULL,
  template_id               uuid NOT NULL REFERENCES public.waiver_templates(id) ON DELETE RESTRICT,
  template_version          bigint NOT NULL,
  signer_name               text NOT NULL,
  consent_flags             jsonb NOT NULL DEFAULT '{}'::jsonb,
  signed_at                 timestamptz NOT NULL DEFAULT now(),
  expires_at                timestamptz NOT NULL,
  ip                        inet,
  user_agent                text,
  waiver_snapshot           text NOT NULL,
  waiver_metadata_snapshot  jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at                timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT member_waiver_signatures_signer_name_not_blank CHECK (length(trim(signer_name)) > 1)
);

CREATE INDEX IF NOT EXISTS member_waiver_signatures_user_signed_idx
  ON public.member_waiver_signatures (user_id, signed_at DESC);

CREATE INDEX IF NOT EXISTS member_waiver_signatures_template_signed_idx
  ON public.member_waiver_signatures (template_id, signed_at DESC);

CREATE INDEX IF NOT EXISTS member_waiver_signatures_user_expires_idx
  ON public.member_waiver_signatures (user_id, expires_at DESC);

CREATE OR REPLACE FUNCTION public.member_waiver_status(p_user_id uuid)
RETURNS TABLE (
  status text,
  active_template_id uuid,
  active_template_version bigint,
  signed_template_id uuid,
  signed_template_version bigint,
  signed_at timestamptz,
  expires_at timestamptz,
  signer_name text
)
LANGUAGE sql
STABLE
AS $$
  WITH active_template AS (
    SELECT wt.id, wt.version
    FROM public.waiver_templates wt
    WHERE wt.is_active = true
    ORDER BY wt.published_at DESC NULLS LAST, wt.created_at DESC
    LIMIT 1
  ),
  latest_signature AS (
    SELECT
      s.id,
      s.template_id,
      s.template_version,
      s.signed_at,
      s.expires_at,
      s.signer_name
    FROM public.member_waiver_signatures s
    WHERE s.user_id = p_user_id
    ORDER BY s.signed_at DESC
    LIMIT 1
  )
  SELECT
    CASE
      WHEN active_template.id IS NULL THEN 'missing'
      WHEN latest_signature.id IS NULL THEN 'missing'
      WHEN latest_signature.template_id <> active_template.id THEN 'stale_version'
      WHEN latest_signature.expires_at <= now() THEN 'expired'
      ELSE 'current'
    END AS status,
    active_template.id AS active_template_id,
    active_template.version AS active_template_version,
    latest_signature.template_id AS signed_template_id,
    latest_signature.template_version AS signed_template_version,
    latest_signature.signed_at AS signed_at,
    latest_signature.expires_at AS expires_at,
    latest_signature.signer_name AS signer_name
  FROM (SELECT 1) AS base
  LEFT JOIN active_template ON true
  LEFT JOIN latest_signature ON true;
$$;

ALTER TABLE public.waiver_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.member_waiver_signatures ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS waiver_templates_select_active_or_admin ON public.waiver_templates;
CREATE POLICY waiver_templates_select_active_or_admin
  ON public.waiver_templates
  FOR SELECT
  TO authenticated
  USING (is_active = true OR public.is_admin());

DROP POLICY IF EXISTS waiver_templates_admin_insert ON public.waiver_templates;
CREATE POLICY waiver_templates_admin_insert
  ON public.waiver_templates
  FOR INSERT
  TO authenticated
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS waiver_templates_admin_update ON public.waiver_templates;
CREATE POLICY waiver_templates_admin_update
  ON public.waiver_templates
  FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS waiver_templates_admin_delete ON public.waiver_templates;
CREATE POLICY waiver_templates_admin_delete
  ON public.waiver_templates
  FOR DELETE
  TO authenticated
  USING (public.is_admin());

DROP POLICY IF EXISTS member_waiver_signatures_select_own_or_admin ON public.member_waiver_signatures;
CREATE POLICY member_waiver_signatures_select_own_or_admin
  ON public.member_waiver_signatures
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id OR public.is_admin());

DROP POLICY IF EXISTS member_waiver_signatures_insert_own_or_admin ON public.member_waiver_signatures;
CREATE POLICY member_waiver_signatures_insert_own_or_admin
  ON public.member_waiver_signatures
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id OR public.is_admin());

DROP POLICY IF EXISTS member_waiver_signatures_admin_update ON public.member_waiver_signatures;
CREATE POLICY member_waiver_signatures_admin_update
  ON public.member_waiver_signatures
  FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS member_waiver_signatures_admin_delete ON public.member_waiver_signatures;
CREATE POLICY member_waiver_signatures_admin_delete
  ON public.member_waiver_signatures
  FOR DELETE
  TO authenticated
  USING (public.is_admin());

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.waiver_templates) THEN
    INSERT INTO public.waiver_templates (
      title,
      body,
      metadata,
      is_active,
      published_at
    )
    VALUES (
      'Film Objektiv Member Waiver and Studio Rules',
      $waiver$
FILM OBJEKTIV MEMBER WAIVER AND STUDIO RULES

1) Safety and Assumption of Risk
- Studio equipment, cables, stands, and powered fixtures can create tripping, electrical, and impact hazards.
- You agree to operate safely, supervise your team/guests, and immediately stop unsafe activity.
- You accept responsibility for injuries or damage arising from unsafe use by you or your guests.

2) Studio Care and Cleanliness
- Return furniture, modifiers, props, and grip equipment to their designated areas.
- Remove all trash, tape, labels, and personal items before leaving.
- Leave the studio in clean, ready-to-use condition for the next member.

3) Equipment Handling and Damage Reporting
- Handle all equipment according to manufacturer and studio instructions.
- Do not force fittings, mounts, locks, or electrical connections.
- Report damaged, missing, or malfunctioning equipment immediately.
- Do not conceal damage or defer reporting to a later visit.

4) Financial Responsibility for Damage
- You are responsible for repair or replacement costs caused by negligent, reckless, or unauthorized use.
- Liability includes damage caused by your assistants, clients, contractors, or invitees.
- Film Objektiv may document incidents and invoice verified costs.

5) Door Access and Security
- Your door/access code is confidential and may not be shared.
- You must ensure doors are secured when entering and leaving.
- You are responsible for activity that occurs under your access session.

6) Prohibited Use
- No illegal activity, unsafe modifications, or prohibited substances.
- No actions that interfere with building operations or create hazards for others.
- No use that violates posted studio operating instructions.

7) Liability Release
- To the fullest extent allowed by law, you release and hold harmless Film Objektiv, its owners, and staff from claims arising from ordinary risks of studio use.
- This release does not apply to gross negligence or intentional misconduct where prohibited by law.

8) Agreement
- By signing, you confirm you have read and understood this waiver and agree to follow all studio rules.
- This signed waiver remains valid for one year, and a new signature is required when it expires or when a new waiver version is published.
      $waiver$,
      jsonb_build_object(
        'documentKey', 'member_waiver_v1',
        'retentionDays', 365,
        'requiresAnnualResign', true,
        'invalidatesOnPublish', true
      ),
      true,
      now()
    );
  END IF;
END
$$;
